### ISSUE TITLE
Package Control Support

### ISSUE THREAD

**Issue by hussani** [florianeckerstorfer/fe-sublime-phpunit#2]
Do you want release this plugin on Package Control?

I think so will leave the instalation more simple for any peoples.

What you think about it?

**Comment by rogeriopradoj** [comment]
Hi, @hussani, nice catch, :+1: !

@florianeckerstorfer, on http://wbond.net/sublime_packages/package_control/package_developers you can get more information about the implementation.

**Comment by florianeckerstorfer** [comment]
There is already a package called `sublime-phpunit`. I will look into it how I can add this package to Package Control.

**Comment by hussani** [comment]
@florianeckerstorfer with package_name_map field into repositories.json will solve the naming problem.
I can put this repository there, but what name do you prefer?
There is already package called "PHPUnit Completions".
I think "PHPUnit Snippets". What you to think about it?

**Comment by florianeckerstorfer** [comment]
PHPUnit Snippets sounds great.

**Comment by hussani** [comment]
All right.
I will put this repository there calling PHPUnit Snippets.
I'll be back when i have news.

**Comment by hussani** [comment]
@florianeckerstorfer I'm sorry. I thought that with package_name_map would solve duplicate names, but the field key is the repository name.
The unique way of solve this is renaming the repository or not publish in Package Control.
It's a issue for you decide. If your choice is  renaming the repo i can put there, otherwise, we stay with manually install (that not hard).

**Comment by florianeckerstorfer** [comment]
Since Github introduced redirects when renaming a repository renaming was no problem any more. The repository is now called fe-sublime-phpunit and I submitted a [PR](https://github.com/wbond/package_control_channel/pull/1418) to include it in Package Control

**Comment by hussani** [comment]
The package finally is on Package Control.
\o
Thanks for create and support this excellent package.
